repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
  - repo: https://github.com/PyCQA/prospector
    rev: v1.9.0
    hooks:
      - id: prospector
        args:
          - --no-autodetect
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
